// Define the Question interface
export interface Question {
  id: number;
  name: string;
  flag: string;
  alternative1: string;
  alternative2: string;
  alternative3: string;
}

// Export the questions array
export const questions: Question[] = [
  {
    id: 1,
    name: "Argentina",
    flag: "public/flags-images/Argentina.jpg",
    alternative1: "Argentina",
    alternative2: "Brazil",
    alternative3: "Canada",
  },
  {
    id: 2,
    name: "Austria",
    flag: "public/flags-images/Austria.jpg",
    alternative1: "France",
    alternative2: "Austria",
    alternative3: "Japan",
  },
  {
    id: 3,
    name: "Chile",
    flag: "public/flags-images/Chile.jpg",
    alternative1: "Mexico",
    alternative2: "Chile",
    alternative3: "Australia",
  },
  {
    id: 4,
    name: "Czech Republic",
    flag: "public/flags-images/Czech_Republic.jpg",
    alternative1: "Italy",
    alternative2: "India",
    alternative3: "Czech Republic",
  },
  {
    id: 5,
    name: "Egypt",
    flag: "public/flags-images/Egypt.jpg",
    alternative1: "Egypt",
    alternative2: "Saudi Arabia",
    alternative3: "Morocco",
  },
  {
    id: 6,
    name: "Estonia",
    flag: "public/flags-images/Estonia.jpg",
    alternative1: "Estonia",
    alternative2: "Latvia",
    alternative3: "Lithuania",
  },
  {
    id: 7,
    name: "Finland",
    flag: "public/flags-images/Finland.jpg",
    alternative1: "Switzerland",
    alternative2: "Finland",
    alternative3: "Norway",
  },
  {
    id: 8,
    name: "Germany",
    flag: "public/flags-images/Germany.jpg",
    alternative1: "United States",
    alternative2: "Germany",
    alternative3: "Poland",
  },
  {
    id: 9,
    name: "Ghana",
    flag: "public/flags-images/Ghana.jpg",
    alternative1: "Nigeria",
    alternative2: "Ghana",
    alternative3: "Kenya",
  },
  {
    id: 10,
    name: "Morocco",
    flag: "public/flags-images/Morocco.jpg",
    alternative1: "Morocco",
    alternative2: "Tunisia",
    alternative3: "Algeria",
  },
  {
    id: 11,
    name: "Norway",
    flag: "public/flags-images/Norway.jpg",
    alternative1: "Sweden",
    alternative2: "Denmark",
    alternative3: "Norway",
  },
  {
    id: 12,
    name: "Portugal",
    flag: "public/flags-images/Portugal.jpg",
    alternative1: "Portugal",
    alternative2: "Brazil",
    alternative3: "Spain",
  },
  {
    id: 13,
    name: "South Africa",
    flag: "public/flags-images/South_Africa.jpg",
    alternative1: "South Africa",
    alternative2: "Zambia",
    alternative3: "Zimbabwe",
  },
  {
    id: 14,
    name: "Spain",
    flag: "public/flags-images/Spain.jpg",
    alternative1: "Portugal",
    alternative2: "Spain",
    alternative3: "Italy",
  },
  {
    id: 15,
    name: "Sweden",
    flag: "public/flags-images/Sweden.jpg",
    alternative1: "Sweden",
    alternative2: "Norway",
    alternative3: "Finland",
  },
  {
    id: 16,
    name: "Thailand",
    flag: "public/flags-images/Thailand.jpg",
    alternative1: "Vietnam",
    alternative2: "Cambodia",
    alternative3: "Thailand",
  },
  {
    id: 17,
    name: "Ukraine",
    flag: "public/flags-images/Ukraine.jpg",
    alternative1: "Ukraine",
    alternative2: "Belarus",
    alternative3: "Russia",
  },
  {
    id: 18,
    name: "United Kingdom",
    flag: "public/flags-images/United_Kingdom.jpg",
    alternative1: "United States",
    alternative2: "Canada",
    alternative3: "United Kingdom",
  },
  {
    id: 19,
    name: "United States",
    flag: "public/flags-images/United_States.jpg",
    alternative1: "United States",
    alternative2: "Mexico",
    alternative3: "Australia",
  },
  {
    id: 20,
    name: "Uruguay",
    flag: "public/flags-images/Uruguay.jpg",
    alternative1: "Uruguay",
    alternative2: "Paraguay",
    alternative3: "Argentina",
  },
];
