// Define the Question interface
export interface Question {
  id: number;
  name: string;
  flag: string;
  alternative1: string;
  alternative2: string;
  alternative3: string;
}

// Export the questions array
export const questions: Question[] = [
  {
    id: 1,
    name: "Argentina",
    flag: "./flags-images/Argentina.jpg",
    alternative1: "Argentina",
    alternative2: "Brazil",
    alternative3: "Canada",
  },
  {
    id: 2,
    name: "Austria",
    flag: "./flags-images/Austria.jpg",
    alternative1: "France",
    alternative2: "Austria",
    alternative3: "Japan",
  },
  {
    id: 3,
    name: "Chile",
    flag: "./flags-images/Chile.jpg",
    alternative1: "Mexico",
    alternative2: "Chile",
    alternative3: "Australia",
  },
  {
    id: 4,
    name: "Czech Republic",
    flag: "./flags-images/Czech_Republic.jpg",
    alternative1: "Italy",
    alternative2: "India",
    alternative3: "Czech Republic",
  },
  {
    id: 5,
    name: "Egypt",
    flag: "./flags-images/Egypt.jpg",
    alternative1: "Saudi Arabia",
    alternative2: "Morocco",
    alternative3: "Egypt",
  },
  {
    id: 6,
    name: "Estonia",
    flag: "./flags-images/Estonia.jpg",
    alternative1: "Estonia",
    alternative2: "Latvia",
    alternative3: "Lithuania",
  },
  {
    id: 7,
    name: "Finland",
    flag: "./flags-images/Finland.jpg",
    alternative1: "Switzerland",
    alternative2: "Finland",
    alternative3: "Norway",
  },
  {
    id: 8,
    name: "Germany",
    flag: "./flags-images/Germany.jpg",
    alternative1: "United States",
    alternative2: "Germany",
    alternative3: "Poland",
  },
  {
    id: 9,
    name: "Ghana",
    flag: "./flags-images/Ghana.jpg",
    alternative1: "Nigeria",
    alternative2: "Ghana",
    alternative3: "Kenya",
  },
  {
    id: 10,
    name: "Morocco",
    flag: "./flags-images/Morocco.jpg",
    alternative1: "Tunisia",
    alternative2: "Morocco",
    alternative3: "Algeria",
  },
  {
    id: 11,
    name: "Norway",
    flag: "./flags-images/Norway.jpg",
    alternative1: "Sweden",
    alternative2: "Denmark",
    alternative3: "Norway",
  },
  {
    id: 12,
    name: "Portugal",
    flag: "./flags-images/Portugal.jpg",
    alternative1: "Portugal",
    alternative2: "Brazil",
    alternative3: "Spain",
  },
  {
    id: 13,
    name: "South Africa",
    flag: "./flags-images/South_Africa.jpg",
    alternative1: "South Africa",
    alternative2: "Zambia",
    alternative3: "Zimbabwe",
  },
  {
    id: 14,
    name: "Spain",
    flag: "./flags-images/Spain.jpg",
    alternative1: "Portugal",
    alternative2: "Spain",
    alternative3: "Italy",
  },
  {
    id: 15,
    name: "Sweden",
    flag: "./flags-images/Sweden.jpg",
    alternative1: "Sweden",
    alternative2: "Norway",
    alternative3: "Finland",
  },
  {
    id: 16,
    name: "Thailand",
    flag: "./flags-images/Thailand.jpg",
    alternative1: "Vietnam",
    alternative2: "Cambodia",
    alternative3: "Thailand",
  },
  {
    id: 17,
    name: "Ukraine",
    flag: "./flags-images/Ukraine.jpg",
    alternative1: "Ukraine",
    alternative2: "Belarus",
    alternative3: "Russia",
  },
  {
    id: 18,
    name: "United Kingdom",
    flag: "./flags-images/United_Kingdom.jpg",
    alternative1: "United States",
    alternative2: "Canada",
    alternative3: "United Kingdom",
  },
  {
    id: 19,
    name: "United States",
    flag: "./flags-images/United_States.jpg",
    alternative1: "United States",
    alternative2: "Mexico",
    alternative3: "Australia",
  },
  {
    id: 20,
    name: "Uruguay",
    flag: "./flags-images/Uruguay.jpg",
    alternative1: "Paraguay",
    alternative2: "Uruguay",
    alternative3: "Argentina",
  },
  {
    id: 21,
    name: "Armenia",
    flag: "./flags-images/Armenia.jpg",
    alternative1: "Romania",
    alternative2: "Azerbaijan",
    alternative3: "Armenia",
  },
  {
    id: 22,
    name: "Hong Kong",
    flag: "./flags-images/Hong_Kong.jpg",
    alternative1: "Vietnam",
    alternative2: "Hong Kong",
    alternative3: "Taiwan",
  },
  {
    id: 23,
    name: "Indonesia",
    flag: "./flags-images/Indonesia.jpg",
    alternative1: "Malaysia",
    alternative2: "Indonesia",
    alternative3: "Philippines",
  },
  {
    id: 24,
    name: "Jamaica",
    flag: "./flags-images/Jamaica.jpg",
    alternative1: "Jamaica",
    alternative2: "Bahamas",
    alternative3: "Cuba",
  },
  {
    id: 25,
    name: "Kazakhstan",
    flag: "./flags-images/Kazakhstan.jpg",
    alternative1: "Kazakhstan",
    alternative2: "Uzbekistan",
    alternative3: "Turkmenistan",
  },
  {
    id: 26,
    name: "Kuwait",
    flag: "./flags-images/Kuwait.jpg",
    alternative1: "Bahrain",
    alternative2: "Kuwait",
    alternative3: "Qatar",
  },
  {
    id: 27,
    name: "Lebanon",
    flag: "./flags-images/Lebanon.jpg",
    alternative1: "Malta",
    alternative2: "Lebanon",
    alternative3: "Jordan",
  },
  {
    id: 28,
    name: "Tunisia",
    flag: "./flags-images/Tunisia.jpg",
    alternative1: "Turkey",
    alternative2: "Algeria",
    alternative3: "Tunisia",
  },
  {
    id: 29,
    name: "Mexico",
    flag: "./flags-images/Mexico.jpg",
    alternative1: "Mexico",
    alternative2: "Guatemala",
    alternative3: "Cuba",
  },
  {
    id: 30,
    name: "Nigeria",
    flag: "./flags-images/Nigeria.jpg",
    alternative1: "Nigeria",
    alternative2: "Ghana",
    alternative3: "Cameroon",
  },
  {
    id: 31,
    name: "Romania",
    flag: "./flags-images/Romania.jpg",
    alternative1: "Romania",
    alternative2: "Austria",
    alternative3: "Bulgaria",
  },
  {
    id: 32,
    name: "Rwanda",
    flag: "./flags-images/Rwanda.jpg",
    alternative1: "Rwanda",
    alternative2: "Uganda",
    alternative3: "Burundi",
  },
  {
    id: 33,
    name: "Senegal",
    flag: "./flags-images/Senegal.jpg",
    alternative1: "Mali",
    alternative2: "Senegal",
    alternative3: "Guinea",
  },
];
